"""initial migration

Revision ID: 2fc709826bb7
Revises: 5b802c1bc4f
Create Date: 2015-12-22 13:45:13.053000

"""

# revision identifiers, used by Alembic.
revision = '2fc709826bb7'
down_revision = '5b802c1bc4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
