"""initial migration

Revision ID: 3736e6cf3c61
Revises: 2fc709826bb7
Create Date: 2015-12-27 14:54:02.068000

"""

# revision identifiers, used by Alembic.
revision = '3736e6cf3c61'
down_revision = '2fc709826bb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
